Q1

In [1]:
import torch
import torch . nn as nn

data = torch . Tensor ([1 , 2 , 3])
softmax_function = nn . Softmax ( dim =0)
output = softmax_function ( data )
assert round ( output [0]. item () , 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

Q2

In [2]:
import torch
import torch . nn as nn

class MySoftmax ( nn . Module ) :
  def __init__ ( self ) :
    super () . __init__ ()

  def forward ( self , x ) :
    ### Your Code Here
    exp_x = torch.exp(x)
    sum_exp_x = torch.sum(exp_x)
    softmax_output = exp_x / sum_exp_x
    return softmax_output
    ### End Code Here

data = torch.Tensor ([5 , 2 , 4])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [ -1]. item () , 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

Q3

In [6]:
import torch
import torch . nn as nn

class MySoftmax ( nn . Module ) :
  def __init__ ( self ) :
    super () . __init__ ()

  def forward ( self , x ) :
    ### Your Code Here
    max_x = torch.max(x)
    exp_x = torch.exp(x - max_x)
    sum_exp_x = torch.sum(exp_x)
    softmax_output = exp_x / sum_exp_x
    return softmax_output
    ### End Code Here

data = torch . Tensor ([1 , 2 , 300000000])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [0]. item () , 2) == 0.0
output

tensor([0., 0., 1.])

Q4

In [7]:
import torch
import torch . nn as nn

class SoftmaxStable ( nn . Module ):
  def __init__ ( self ) :
    super () . __init__ ()

  def forward ( self , x ) :
    x_max = torch .max(x , dim =0 , keepdims = True )
    x_exp = torch . exp ( x - x_max . values )
    partition = x_exp .sum (0 , keepdims = True )
    return x_exp / partition

data = torch . Tensor ([1 , 2 , 3])
softmax_stable = SoftmaxStable ()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

Q5

In [10]:
from abc import ABC , abstractmethod

class Person ( ABC ) :
  def __init__ ( self , name :str , yob :int ) :
    self . _name = name
    self . _yob = yob

  def get_yob ( self ) :
    return self . _yob

  @abstractmethod
  def describe ( self ) :
    pass

class Student ( Person ) :
  def __init__ ( self , name :str , yob :int , grade :str) :
    ### Your Code Here
    super().__init__(name, yob)
    self._grade = grade
    ### End Code Here

  def describe ( self ) :
    ### Your Code Here
    print(f"Name: {self._name}, Year of Birth: {self._yob}, Grade: {self._grade}")
    ### End Code Here

student1 = Student ( name =" studentZ2023 ", yob =2011 , grade ="6")
assert student1 . _yob == 2011
student1 . describe ()

Name:  studentZ2023 , Year of Birth: 2011, Grade: 6


Q6

In [11]:
from abc import ABC , abstractmethod

class Person ( ABC ) :
  def __init__ ( self , name :str , yob :int ) :
    self . _name = name
    self . _yob = yob

  def get_yob ( self ) :
    return self . _yob

  @abstractmethod
  def describe ( self ) :
    pass

class Teacher ( Person ) :
  def __init__ ( self , name :str , yob :int , subject : str) :
    ### Your Code Here
    super().__init__(name, yob)
    self._subject = subject
    ### End Code Here

  def describe ( self ) :
    ### Your Code Here
    print(f"Name: {self._name}, Year of Birth: {self._yob}, Subject: {self._subject}")
    ### End Code Here

teacher1 = Teacher ( name =" teacherZ2023 ", yob =1991 , subject =" History ")
assert teacher1 . _yob == 1991
teacher1 . describe ()

Name:  teacherZ2023 , Year of Birth: 1991, Subject:  History 


Q7

In [13]:
from abc import ABC , abstractmethod

class Person ( ABC ) :
  def __init__ ( self , name :str , yob :int ) :
    self . _name = name
    self . _yob = yob

  def get_yob ( self ) :
    return self . _yob

  @abstractmethod
  def describe ( self ) :
    pass

class Doctor ( Person ) :
  def __init__ ( self , name :str , yob :int , specialist :str) :
    ### Your Code Here
    super().__init__(name, yob)
    self._specialist = specialist
    ### End Code Here

  def describe ( self ) :
    ### Your Code Here
    print(f"Name: {self._name}, Year of Birth: {self._yob}, Specialist: {self._specialist}")
    ### End Code Here

doctor1 = Doctor ( name =" doctorZ2023 ", yob =1981 , specialist =" Endocrinologists ")
assert doctor1 . _yob == 1981
doctor1 . describe ()

Name:  doctorZ2023 , Year of Birth: 1981, Specialist:  Endocrinologists 


Q8

In [24]:
class Ward :
  def __init__ ( self , name : str) :
    self . __name = name
    self . __listPeople = list ()

  def add_person ( self , person : Person ) :
    self . __listPeople . append ( person )

  def describe ( self ) :
    print ( f" Ward Name : { self . __name }")
    for p in self . __listPeople :
      p.describe ()

  def count_doctor ( self ) :
    ### Your Code Here
    count = 0
    for p in self.__listPeople:
      if isinstance(p, Doctor):
        count += 1
    return count
    ### End Code Here

student1 = Student ( name =" studentA ", yob =2010 , grade ="7")
teacher1 = Teacher ( name =" teacherA ", yob =1969 , subject =" Math ")
teacher2 = Teacher ( name =" teacherB ", yob =1995 , subject =" History ")
doctor1 = Doctor ( name =" doctorA ", yob =1945 , specialist =" Endocrinologists ")

doctor2 = Doctor ( name =" doctorB ", yob =1975 , specialist =" Cardiologists ")
ward1 = Ward ( name =" Ward1 ")
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
ward1 . add_person ( doctor2 )
assert ward1 . count_doctor () == 2
ward1 . count_doctor ()


2

Q9

In [25]:
class MyStack :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __stack = []

  def is_full ( self ) :
    return len( self . __stack ) == self . __capacity

  def push ( self , value ) :
    ### Your Code Here
    if not self.is_full():
      self.__stack.append(value)
    ### End Code Here

stack1 = MyStack ( capacity =5)
stack1 . push (1)
assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . is_full () )

False


Q10

In [26]:
class MyStack :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __stack = []

  def is_full ( self ) :
    return len( self . __stack ) == self . __capacity

  def push ( self , value ) :
    ### Your Code Here
    if not self.is_full():
      self.__stack.append(value)
    ### End Code Here

  def top ( self ) :
    ### Your Code Here
    if not self.__stack:
      return None
    return self.__stack[-1]
    # End Code Here

stack1 = MyStack ( capacity =5)
stack1 . push (1)
assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . top () )

2


Q11

In [27]:
class MyQueue :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __queue = []

  def is_full ( self ) :
    return len( self . __queue ) == self . __capacity

  def enqueue ( self , value ) :
    ### Your Code Here
    if not self.is_full():
      self.__queue.append(value)
    ### End Code Here

queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
assert queue1 . is_full () == False
queue1 . enqueue (2)
print ( queue1 . is_full () )

False


Q12

In [28]:
class MyQueue :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __queue = []

  def isEmpty ( self ) :
    return len( self . __queue ) == 0

  def is_full ( self ) :
    return len( self . __queue ) == self . __capacity

  def dequeue ( self ) :
    if not self.isEmpty():
      return self.__queue.pop(0)

  def enqueue ( self , value ) :
    if not self.is_full():
      self.__queue.append(value)

  def front ( self ) :
    ### Your Code Here
    if not self.isEmpty():
      return self.__queue[0]
    ### End Code Here

queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
assert queue1 . is_full () == False
queue1 . enqueue (2)
print ( queue1 . front () )

1
